image: golang:1.13

cache:
  paths:
    - .cache

stages:
  - test
  - build

before_script:
  - mkdir -p /tmp/cache
  - export GOPATH="/tmp/cache"

unit_test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make build
