language: go
dist: xenial

go: 1.13.x

services:
  - mysql

env:
  - SNIPPETBOX_DB_USER=root SNIPPETBOX_DB_PASSWORD= SNIPPETBOX_DB_ADDRESS=127.0.0.1

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS snippetbox;'
  - mysql -e 'SHOW DATABASES;'
  - mysql -u root snippetbox < ./pkg/models/mysql/testdata/setup.sql

jobs:
  include:
    - stage: 'tests'
      name: 'unit tests'
      script: make test
    - name: 'check version'
    - name: 'integration tests'
      script: make integrate
